# Generated by Django 3.1.7 on 2021-03-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.ManyToManyField(to='notes.Labels'),
        ),
    ]
